name: CI - macOS

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
      - "feature/*"
      - "hotfix/*"
      - "release/*"
      - "fixes/*"
  push:
    branches:
      - main
      - develop

jobs:
  pre-commit:
    name: Pre-commit CI (macOS)
    runs-on: macos-12
    if: (github.event.pull_request.draft == false && contains(github.event.pull_request.labels.*.name, 'macos-ci-test'))
    strategy:
      matrix:
        python-version: ["3.12"]
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # this is required due to the docker dependency for the secret scanning tool TruffleHog
      - name: Setup docker (not included on macOS runners)
        run: |
          brew install docker
          colima start

      - name: Run Pre-commit
        uses: pre-commit/action@v3.0.0
