name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
      - "feature/*"
      - "hotfix/*"
      - "release/*"
      - "fixes/*"
  push:
    branches:
      - main
      - develop

jobs:
  pre-commit:
    name: Pre-commit CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Pre-commit
        uses: pre-commit/action@v3.0.0
