name: Poetry Update

on:
  # Run weekly on Monday at 0700AM
  schedule:
    - cron: "0 7 * * MON"
  # Allow a manual trigger
  workflow_dispatch:

jobs:
  auto-update-ubuntu:
    runs-on: ubuntu-latest
    steps:
        - uses: fuzzylabs/gha-poetry-update@v1
          with:
            python-version: "3.12"

  auto-update-macos:
    runs-on: macos-12
    steps:
        - uses: fuzzylabs/gha-poetry-update@v1
          with:
            python-version: "3.12"
